/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/jobs/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Job
         * @description Submit a job URL for extraction.
         *     Returns a job record immediately; extraction runs in background.
         */
        post: operations["extract_job_api_v1_jobs_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Get job extraction result.
         */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Resume Upload
         * @description Parse an uploaded PDF/DOCX/TXT resume into structured ResumeSchema.
         *     User can edit the result before saving as their base resume.
         */
        post: operations["parse_resume_upload_api_v1_resumes_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Resume
         * @description Save a base resume.
         */
        post: operations["create_resume_api_v1_resumes__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Resume */
        get: operations["get_resume_api_v1_resumes__resume_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/personalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Personalize Resume
         * @description Personalize a saved resume for a given JD. Synchronous — use for preview.
         */
        post: operations["personalize_resume_api_v1_resumes__resume_id__personalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Application
         * @description Queue a job application. Returns immediately; use /stream to follow progress.
         */
        post: operations["submit_application_api_v1_applications__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Status
         * @description SSE stream of ApplicationStatusEvent objects for real-time status updates.
         *
         *     Subscribes to Redis pub/sub channel app:{application_id}.
         *     Terminates when status enters a terminal state.
         */
        get: operations["stream_status_api_v1_applications__application_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Application
         * @description Get current application state.
         */
        get: operations["get_application_api_v1_applications__application_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Api Keys
         * @description List configured providers (keys masked).
         */
        get: operations["list_api_keys_api_v1_settings_api_keys_get"];
        put?: never;
        /**
         * Save Api Key
         * @description Encrypt and persist a user's API key. Upserts by (user_id, provider).
         */
        post: operations["save_api_key_api_v1_settings_api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/api-keys/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Api Key */
        delete: operations["delete_api_key_api_v1_settings_api_keys__provider__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/deep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Deep */
        get: operations["health_deep_health_deep_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiKeyRequest */
        ApiKeyRequest: {
            provider: components["schemas"]["LLMProvider"];
            /** Api Key */
            api_key: string;
        };
        /** ApiKeyResponse */
        ApiKeyResponse: {
            provider: components["schemas"]["LLMProvider"];
            /** Is Active */
            is_active: boolean;
            /** Masked Key */
            masked_key: string;
        };
        /** ApplicationCreateRequest */
        ApplicationCreateRequest: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Resume Id
             * Format: uuid
             */
            resume_id: string;
            /** @default ats */
            theme: components["schemas"]["CVTheme"];
            /**
             * Generate Cover Letter
             * @default false
             */
            generate_cover_letter: boolean;
        };
        /** ApplicationResponse */
        ApplicationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Resume Id
             * Format: uuid
             */
            resume_id: string;
            status: components["schemas"]["ApplicationStatus"];
            /** Cv Url */
            cv_url?: string | null;
            /** Error */
            error?: string | null;
            /** Attempts */
            attempts: number;
        };
        /**
         * ApplicationStatus
         * @enum {string}
         */
        ApplicationStatus: "queued" | "processing" | "generating_cv" | "filling_form" | "submitted" | "failed" | "requires_human";
        /** Body_parse_resume_upload_api_v1_resumes_parse_post */
        Body_parse_resume_upload_api_v1_resumes_parse_post: {
            /** File */
            file: string;
        };
        /**
         * CVTheme
         * @enum {string}
         */
        CVTheme: "ats" | "modern" | "creative" | "portfolio";
        /** CertificationEntry */
        CertificationEntry: {
            /** Name */
            name: string;
            /** Issuer */
            issuer: string;
            /** Date */
            date?: null;
            /** Url */
            url?: string | null;
        };
        /** EducationEntry */
        EducationEntry: {
            /** Institution */
            institution: string;
            /** Degree */
            degree: string;
            /** Field */
            field?: string | null;
            /** Year */
            year: number;
        };
        /** ExperienceEntry */
        ExperienceEntry: {
            /** Company */
            company: string;
            /** Role */
            role: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /** End */
            end?: string | null;
            /** Location */
            location?: string | null;
            /** Bullets */
            bullets?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JDSchema
         * @description Extracted, normalized job description.
         */
        JDSchema: {
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Location */
            location?: string | null;
            /** Remote */
            remote?: boolean | null;
            /** Employment Type */
            employment_type?: string | null;
            /** Experience Level */
            experience_level?: string | null;
            /** Skills Required */
            skills_required?: string[];
            /** Skills Preferred */
            skills_preferred?: string[];
            /** Description */
            description: string;
            /** Salary Min */
            salary_min?: number | null;
            /** Salary Max */
            salary_max?: number | null;
            /** Salary Currency */
            salary_currency?: string | null;
            /** Apply Url */
            apply_url?: string | null;
        };
        /** JobCreateRequest */
        JobCreateRequest: {
            /** Url */
            url: string;
        };
        /** JobResponse */
        JobResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Url */
            url: string;
            status: components["schemas"]["JobStatus"];
            jd?: components["schemas"]["JDSchema"] | null;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "pending" | "extracting" | "extracted" | "failed";
        /**
         * LLMProvider
         * @enum {string}
         */
        LLMProvider: "anthropic" | "openai" | "gemini" | "ollama";
        /** ProjectEntry */
        ProjectEntry: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Url */
            url?: string | null;
            /** Tech */
            tech?: string[];
            /** Bullets */
            bullets?: string[];
        };
        /** ResumeCreateRequest */
        ResumeCreateRequest: {
            /** Name */
            name: string;
            data: components["schemas"]["ResumeSchema"];
            /**
             * Is Base
             * @default false
             */
            is_base: boolean;
        };
        /** ResumeResponse */
        ResumeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            data: components["schemas"]["ResumeSchema"];
            /** Is Base */
            is_base: boolean;
        };
        /**
         * ResumeSchema
         * @description Canonical resume structure — do not modify without updating shared-types.
         */
        ResumeSchema: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone?: string | null;
            /** Location */
            location?: string | null;
            /** Summary */
            summary?: string | null;
            /** Linkedin */
            linkedin?: string | null;
            /** Github */
            github?: string | null;
            /** Portfolio */
            portfolio?: string | null;
            /** Skills */
            skills?: string[];
            /** Experience */
            experience?: components["schemas"]["ExperienceEntry"][];
            /** Education */
            education?: components["schemas"]["EducationEntry"][];
            /** Projects */
            projects?: components["schemas"]["ProjectEntry"][];
            /** Certifications */
            certifications?: components["schemas"]["CertificationEntry"][];
        };
        /**
         * TailoredResumeSchema
         * @description Resume after personalization — includes metadata about changes.
         */
        TailoredResumeSchema: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone?: string | null;
            /** Location */
            location?: string | null;
            /** Summary */
            summary?: string | null;
            /** Linkedin */
            linkedin?: string | null;
            /** Github */
            github?: string | null;
            /** Portfolio */
            portfolio?: string | null;
            /** Skills */
            skills?: string[];
            /** Experience */
            experience?: components["schemas"]["ExperienceEntry"][];
            /** Education */
            education?: components["schemas"]["EducationEntry"][];
            /** Projects */
            projects?: components["schemas"]["ProjectEntry"][];
            /** Certifications */
            certifications?: components["schemas"]["CertificationEntry"][];
            /** Tailored For Job Id */
            tailored_for_job_id?: string | null;
            /** Ats Score */
            ats_score?: number | null;
            /** Keyword Coverage */
            keyword_coverage?: number | null;
            /** Changes Summary */
            changes_summary?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    extract_job_api_v1_jobs_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_resume_upload_api_v1_resumes_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_resume_upload_api_v1_resumes_parse_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_resume_api_v1_resumes__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_api_v1_resumes__resume_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    personalize_resume_api_v1_resumes__resume_id__personalize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JDSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TailoredResumeSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_application_api_v1_applications__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_status_api_v1_applications__application_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_application_api_v1_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_api_keys_api_v1_settings_api_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyResponse"][];
                };
            };
        };
    };
    save_api_key_api_v1_settings_api_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_key_api_v1_settings_api_keys__provider__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["schemas"]["LLMProvider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_deep_health_deep_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
